[server]
disconnectedSessionTTL = 3600
websocketPingInterval = 30
websocketPingTimeout = 30
enableWebsocketCompression = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
base = "dark"
