[global]
developmentMode = false

[server]
disconnectedSessionTTL = 3600
websocketPingInterval = 30
websocketPingTimeout = 30
enableWebsocketCompression = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#E63946"
backgroundColor = "#1a1a2e"
secondaryBackgroundColor = "#16213e"
textColor = "#FAFAFA"
font = "sans serif"

[client]
toolbarMode = "minimal"
